import {
  Activity,
  BarChart3,
  Bell,
  BookOpen,
  Bot,
  BriefcaseBusiness,
  Building2,
  Database,
  FileArchive,
  FileText,
  FolderOpen,
  Globe,
  GraduationCap,
  HeartHandshake,
  Home,
  KeyRound,
  Languages,
  LayoutDashboard,
  LifeBuoy,
  Link2,
  Lock,
  Menu,
  MessageSquare,
  Palette,
  Search,
  Shield,
  Smartphone,
  Ticket,
  Users,
  Workflow,
  Zap,
  type LucideIcon,
} from "lucide-react"

export type AdminModule = {
  slug: string
  title: string
  description: string
  icon: LucideIcon
  status: "Live" | "Ready" | "Planned"
  metrics: { label: string; value: string; trend: string }[]
  actions: string[]
  features: string[]
  workflows: string[]
}

export const adminModules: AdminModule[] = [
  {
    slug: "website",
    title: "Website Management",
    description: "Control branding, pages, SEO, maintenance, scripts, cache, and public website structure.",
    icon: Globe,
    status: "Ready",
    metrics: [
      { label: "Published pages", value: "18", trend: "+3 this month" },
      { label: "SEO score", value: "91%", trend: "Healthy" },
      { label: "Cache hit rate", value: "84%", trend: "+9%" },
    ],
    actions: ["Edit branding", "Manage homepage", "Toggle maintenance", "Clear cache"],
    features: [
      "Website settings",
      "Branding, logo, favicon, colors, and typography",
      "Header, footer, homepage, and navigation managers",
      "SEO settings, sitemap generator, robots.txt editor",
      "Custom CSS and JavaScript controls",
      "Maintenance mode and cache management",
    ],
    workflows: ["Draft changes", "Preview public site", "Publish version", "Audit release"],
  },
  {
    slug: "navigation",
    title: "Navigation Management",
    description: "Build responsive menus, mega menus, breadcrumbs, footer links, and dynamic visibility rules.",
    icon: Menu,
    status: "Ready",
    metrics: [
      { label: "Menu items", value: "42", trend: "Across 5 menus" },
      { label: "Hidden items", value: "6", trend: "Role based" },
      { label: "Mobile health", value: "100%", trend: "Responsive" },
    ],
    actions: ["Upload logo", "Open menu builder", "Create mega menu", "Edit breadcrumbs"],
    features: [
      "Desktop, mobile, footer, and breadcrumb navigation",
      "Logo size, position, and variant controls",
      "Drag and drop menu builder",
      "Dropdown and mega menu composition",
      "Show or hide items by role, page, device, or status",
    ],
    workflows: ["Add menu item", "Configure visibility", "Reorder structure", "Publish navigation"],
  },
  {
    slug: "teams",
    title: "Team Management",
    description: "Manage organizations, departments, invitations, team roles, permissions, and member activity.",
    icon: Building2,
    status: "Ready",
    metrics: [
      { label: "Organizations", value: "12", trend: "+2" },
      { label: "Departments", value: "36", trend: "Mapped" },
      { label: "Pending invites", value: "9", trend: "Needs review" },
    ],
    actions: ["Create team", "Invite members", "Review activity", "Configure departments"],
    features: [
      "Team dashboards and profiles",
      "Organization and department management",
      "Team invitations, roles, and permissions",
      "Member activity and notifications",
      "Organization admin controls",
    ],
    workflows: ["Create organization", "Add departments", "Invite members", "Assign team roles"],
  },
  {
    slug: "permissions",
    title: "Authorization & Permissions",
    description: "Enterprise RBAC for admins, faculty, mentors, students, support, finance, marketing, and custom roles.",
    icon: KeyRound,
    status: "Ready",
    metrics: [
      { label: "System roles", value: "12", trend: "Default set" },
      { label: "Custom roles", value: "4", trend: "+1 draft" },
      { label: "Permission groups", value: "15", trend: "Granular" },
    ],
    actions: ["Create role", "Edit matrix", "Review access", "Export policy"],
    features: [
      "Super admin, admin, manager, faculty, mentor, student, moderator, support, finance, marketing, team member, and organization admin roles",
      "Custom role creation",
      "View, create, edit, delete, publish, approve, reject, export, import permissions",
      "Module-specific access for users, website, courses, teams, payments, forms, and reports",
    ],
    workflows: ["Define role", "Select permissions", "Assign users", "Audit changes"],
  },
  {
    slug: "authentication",
    title: "Authentication",
    description: "Manage login portals, secure sessions, email verification, recovery, MFA, and device history.",
    icon: Lock,
    status: "Ready",
    metrics: [
      { label: "Active sessions", value: "128", trend: "+14 today" },
      { label: "MFA adoption", value: "38%", trend: "+5%" },
      { label: "Failed logins", value: "7", trend: "Low risk" },
    ],
    actions: ["Configure portals", "Review devices", "Set timeout", "Require MFA"],
    features: [
      "Student, user, admin, faculty, staff, and hidden team portals",
      "JWT and refresh-token session strategy planning",
      "Device sessions and login history",
      "Email verification and password recovery",
      "Multi-factor authentication and session timeout controls",
    ],
    workflows: ["Select portal", "Set access rules", "Configure session policy", "Monitor login history"],
  },
  {
    slug: "forms",
    title: "Registration Form Builder",
    description: "Create multi-step forms with validation, conditional logic, uploads, templates, analytics, and exports.",
    icon: FileText,
    status: "Ready",
    metrics: [
      { label: "Published forms", value: "11", trend: "+2" },
      { label: "Responses", value: "4.8k", trend: "+18%" },
      { label: "Conversion", value: "62%", trend: "+4%" },
    ],
    actions: ["Create form", "Open builder", "View responses", "Export CSV"],
    features: [
      "Create, edit, duplicate, draft, publish, and delete forms",
      "Drag and drop multi-step form builder",
      "Templates, conditional logic, required fields, file and image upload",
      "Email, SMS, and auto-response notifications",
      "Response dashboard with CSV, Excel, and PDF export",
    ],
    workflows: ["Pick template", "Build fields", "Configure logic", "Publish and track"],
  },
  {
    slug: "community-admin",
    title: "Community Management",
    description: "Moderate feed, forums, groups, clubs, Q&A, mentorship, events, networking, and reports.",
    icon: MessageSquare,
    status: "Ready",
    metrics: [
      { label: "Posts today", value: "236", trend: "+11%" },
      { label: "Open reports", value: "14", trend: "Moderate" },
      { label: "Active groups", value: "29", trend: "+3" },
    ],
    actions: ["Review reports", "Create group", "Pin announcement", "Moderate posts"],
    features: [
      "Community feed, posts, comments, likes, shares, and polls",
      "Discussion forums, Q&A, groups, clubs, and communities",
      "Mentorship, events, and networking management",
      "Moderation queues and community reporting",
    ],
    workflows: ["Review flagged content", "Apply moderation action", "Notify user", "Log decision"],
  },
  {
    slug: "search-admin",
    title: "Search System",
    description: "Configure global indexed search across users, courses, lessons, blogs, teams, forms, and announcements.",
    icon: Search,
    status: "Ready",
    metrics: [
      { label: "Indexed records", value: "28k", trend: "+2.4k" },
      { label: "Avg latency", value: "74ms", trend: "Fast" },
      { label: "No-result rate", value: "3.1%", trend: "-0.8%" },
    ],
    actions: ["Rebuild index", "Edit filters", "Review trends", "Tune synonyms"],
    features: [
      "Global, instant, fuzzy, AI, voice, and category search controls",
      "Autocomplete, live suggestions, typo correction, and recent searches",
      "Smart filters, tag search, history, trending searches",
      "Index coverage for users, courses, lessons, blogs, events, communities, documentation, teams, forms, and announcements",
    ],
    workflows: ["Select sources", "Configure facets", "Rebuild index", "Analyze search quality"],
  },
  {
    slug: "files",
    title: "File Manager",
    description: "Central media library for images, videos, audio, PDFs, documents, folders, previews, and versions.",
    icon: FolderOpen,
    status: "Ready",
    metrics: [
      { label: "Assets", value: "8.2k", trend: "+420" },
      { label: "Storage", value: "214 GB", trend: "71% used" },
      { label: "Versions", value: "1.6k", trend: "Tracked" },
    ],
    actions: ["Upload files", "Create folder", "Review storage", "Open library"],
    features: [
      "Image, video, audio, PDF, and document upload",
      "Folder management and media library",
      "Search files and preview assets",
      "Version history and storage analytics",
    ],
    workflows: ["Upload asset", "Tag metadata", "Place in folder", "Publish or archive"],
  },
  {
    slug: "notifications",
    title: "Notification Center",
    description: "Coordinate email, push, in-app, SMS, broadcasts, banners, user alerts, and scheduled messages.",
    icon: Bell,
    status: "Ready",
    metrics: [
      { label: "Sent today", value: "9.4k", trend: "+16%" },
      { label: "Open rate", value: "48%", trend: "+3%" },
      { label: "Scheduled", value: "17", trend: "Queued" },
    ],
    actions: ["Create broadcast", "Schedule message", "Edit banner", "Manage preferences"],
    features: [
      "Email, push, in-app, and SMS notifications",
      "Broadcast messages and announcement banners",
      "User alerts and scheduled notifications",
      "Notification preferences and channel controls",
    ],
    workflows: ["Choose audience", "Compose message", "Schedule delivery", "Review engagement"],
  },
  {
    slug: "mobile",
    title: "Mobile Experience",
    description: "Manage responsive dashboard, sidebar, hamburger navigation, mobile forms, tablet support, and PWA readiness.",
    icon: Smartphone,
    status: "Ready",
    metrics: [
      { label: "Mobile users", value: "64%", trend: "+7%" },
      { label: "PWA score", value: "92", trend: "Installable" },
      { label: "Touch issues", value: "0", trend: "Clean" },
    ],
    actions: ["Preview mobile", "Configure PWA", "Test navigation", "Review forms"],
    features: [
      "Responsive dashboard, sidebar, navigation, search, and forms",
      "Working hamburger menus and tablet layouts",
      "Smooth animations and touch gesture readiness",
      "Progressive Web App configuration",
    ],
    workflows: ["Select viewport", "Run responsive checks", "Fix issues", "Publish mobile build"],
  },
  {
    slug: "security",
    title: "Security Center",
    description: "Manage protected routes, RBAC, audit logs, login monitoring, device management, API security, and rate limits.",
    icon: Shield,
    status: "Ready",
    metrics: [
      { label: "Risk score", value: "Low", trend: "Stable" },
      { label: "Audit events", value: "12.7k", trend: "+8%" },
      { label: "Blocked attempts", value: "31", trend: "Today" },
    ],
    actions: ["Review audit logs", "Set rate limits", "Manage devices", "Export security report"],
    features: [
      "RBAC, protected routes, and permission validation",
      "API security, CSRF protection, rate limiting, and secure cookies",
      "Audit logs, login monitoring, activity tracking, and device management",
      "Session timeout, encryption planning, and security reports",
    ],
    workflows: ["Review event", "Classify risk", "Take action", "Record audit trail"],
  },
  {
    slug: "integrations",
    title: "Integrations & API",
    description: "Manage API access, webhooks, third-party integrations, credentials, status, and operational logs.",
    icon: Link2,
    status: "Ready",
    metrics: [
      { label: "Connected apps", value: "8", trend: "+1" },
      { label: "Webhook success", value: "99.2%", trend: "Healthy" },
      { label: "API errors", value: "12", trend: "-6%" },
    ],
    actions: ["Create API key", "Add webhook", "View logs", "Test integration"],
    features: [
      "API management and scoped keys",
      "Webhook configuration and delivery logs",
      "Integration settings and credentials",
      "Error monitoring and status checks",
    ],
    workflows: ["Register integration", "Set scopes", "Test delivery", "Monitor logs"],
  },
  {
    slug: "support",
    title: "Support Operations",
    description: "Manage tickets, feedback, contact requests, help center, changelog, versions, backups, imports, and exports.",
    icon: LifeBuoy,
    status: "Ready",
    metrics: [
      { label: "Open tickets", value: "23", trend: "-4" },
      { label: "SLA health", value: "96%", trend: "On track" },
      { label: "Feedback items", value: "118", trend: "+12" },
    ],
    actions: ["Open tickets", "Review feedback", "Publish changelog", "Run backup"],
    features: [
      "Feedback and contact management",
      "Help center and support ticket system",
      "Changelog, version management, backup and restore",
      "Import, export, system logs, and operational monitoring",
    ],
    workflows: ["Triage request", "Assign owner", "Resolve issue", "Publish learning"],
  },
]

export const adminNavGroups = [
  {
    label: "Command",
    items: [
      { href: "/admin", label: "Dashboard", icon: LayoutDashboard },
      { href: "/admin/analytics", label: "Analytics", icon: BarChart3 },
      { href: "/admin/reports", label: "Reports", icon: Activity },
    ],
  },
  {
    label: "Platform",
    items: [
      { href: "/admin/website", label: "Website", icon: Globe },
      { href: "/admin/navigation", label: "Navigation", icon: Menu },
      { href: "/admin/website", label: "Branding", icon: Palette },
      { href: "/admin/security", label: "Security", icon: Shield },
    ],
  },
  {
    label: "People",
    items: [
      { href: "/admin/users", label: "Users", icon: Users },
      { href: "/admin/teams", label: "Teams", icon: Building2 },
      { href: "/admin/permissions", label: "Permissions", icon: KeyRound },
      { href: "/admin/authentication", label: "Authentication", icon: Lock },
    ],
  },
  {
    label: "Learning",
    items: [
      { href: "/admin/courses", label: "Courses", icon: BookOpen },
      { href: "/admin/forms", label: "Forms", icon: FileText },
      { href: "/admin/community-admin", label: "Community", icon: MessageSquare },
      { href: "/admin/search-admin", label: "Search", icon: Search },
    ],
  },
  {
    label: "Operations",
    items: [
      { href: "/admin/files", label: "Files", icon: FolderOpen },
      { href: "/admin/notifications", label: "Notifications", icon: Bell },
      { href: "/admin/mobile", label: "Mobile", icon: Smartphone },
      { href: "/admin/integrations", label: "Integrations", icon: Link2 },
      { href: "/admin/support", label: "Support", icon: LifeBuoy },
    ],
  },
]

export const dashboardCapabilities = [
  { label: "Website", icon: Home, href: "/admin/website" },
  { label: "Branding", icon: Palette, href: "/admin/website" },
  { label: "Content", icon: FileArchive, href: "/admin/website" },
  { label: "Users", icon: Users, href: "/admin/users" },
  { label: "Teams", icon: Building2, href: "/admin/teams" },
  { label: "RBAC", icon: KeyRound, href: "/admin/permissions" },
  { label: "Auth", icon: Lock, href: "/admin/authentication" },
  { label: "Forms", icon: FileText, href: "/admin/forms" },
  { label: "Courses", icon: GraduationCap, href: "/admin/courses" },
  { label: "Community", icon: HeartHandshake, href: "/admin/community-admin" },
  { label: "Search", icon: Search, href: "/admin/search-admin" },
  { label: "Files", icon: FolderOpen, href: "/admin/files" },
  { label: "Notifications", icon: Bell, href: "/admin/notifications" },
  { label: "Reports", icon: BarChart3, href: "/admin/reports" },
  { label: "Mobile", icon: Smartphone, href: "/admin/mobile" },
  { label: "Security", icon: Shield, href: "/admin/security" },
  { label: "Languages", icon: Languages, href: "/admin/settings" },
  { label: "Support", icon: Ticket, href: "/admin/support" },
  { label: "API", icon: Bot, href: "/admin/integrations" },
  { label: "Backups", icon: Database, href: "/admin/support" },
  { label: "Workflows", icon: Workflow, href: "/admin/forms" },
  { label: "Performance", icon: Zap, href: "/admin/analytics" },
  { label: "Careers", icon: BriefcaseBusiness, href: "/admin/website" },
]
